package lib

const ADDRESS_PREFIX = "allo" // each address prefixed by this
const DEFAULT_BOND_DENOM = "uallo"
const ALLORA_OFFCHAIN_NODE_CONFIG_JSON = "ALLORA_OFFCHAIN_NODE_CONFIG_JSON"
const ALLORA_OFFCHAIN_NODE_CONFIG_FILE_PATH = "ALLORA_OFFCHAIN_NODE_CONFIG_FILE_PATH"
